### ISSUE TITLE
UI Improvement: Automatically remove the all choice when a new choice option is selected

### ISSUE THREAD

**Issue by tushortz** [hypy13/django-daisy#18]
I struggled with this for a while until i realised that when i am filtering, i have to manually remove the `all` choice as well otherwise there would be no result

<img width="568" alt="Image" src="https://github.com/user-attachments/assets/2c4259d0-eabf-4a65-bcb6-52a05fe4c812" />

**Comment by hypy13** [comment]
Hi again, Sorry for the delay.
Could you clarify the filtering field type you're using? 
Is it a custom filter?
 
I’m not seeing this issue currently, and the "all" option isn’t selected by default for me. 
I have noticed a similar issue with the date filtering field, though.
Can you share more specifics so I can look into it?

**Comment by hypy13** [comment]
please check the new update:
 v1.0.22

**Comment by tushortz** [comment]
this is fixed thanks but there is another bug 😄 .

If i choose two items to filter by, it only selects and filters by the first  

<img width="373" alt="Image" src="https://github.com/user-attachments/assets/ee7d1316-cb63-4620-bb6f-e796f74e7fb7" />

<img width="280" alt="Image" src="https://github.com/user-attachments/assets/45931216-3470-4874-bd36-840425f1739f" />

**Comment by tushortz** [comment]
The default django admin only does 1 at a time filtering (which is the intended feature). I raised thisthis is a bug because the select 
 allows me to choose multiple filtering.

There are two options:
- prevent users from selecting multiple filters
- allow multiple selects and fix it as a bug

i'd actually love the second option if possible

**Comment by hypy13** [comment]
thanks a lot for support @tushortz 
can you please update to new version v1.0.23
can check new filter?

**Comment by hypy13** [comment]
Unfortunatly "All" option is still exist but its not affecting filter result :)

**Comment by tushortz** [comment]
ok thanks for this. at least it's still usable for now
